"global": 
  "resolve_timeout": "5m"
"receivers":
- "name": "slack_alert1"
  "slack_configs":
  - "api_url": "https://hooks.slack.com/services/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"
    "channel": "#alert_1"
- "name": "slack_alert2"
  "slack_configs":
  - "api_url": "https://hooks.slack.com/services/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"
    "channel": "#alert_2"
    "title": "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
    "text": "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
"route": 
  "receiver": "slack_alert1"
  "group_interval": "1m"
  "group_wait": "30s"
  "repeat_interval": "3m"
  "group_by": 
  - "job"
  "routes": 
  - "match_re":
      "alertname": "^NGINX.*"
    "receiver": "slack_alert2"
