apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: prometheus-example-rules
  namespace: monitoring
spec:
  groups:
  - name: yourname.rules
    rules:
    - alert: YournameAlert
      expr: vector(1)
