apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: prometheus-example-rules2
  namespace: monitoring
spec:
  groups:
  - name: nginx_rule
    rules:
    - alert: NGINXAlert
      expr: nginx_ingress_controller_nginx_process_requests_total > 1000
      annotations:
        description: '{{ $labels.instance }} of job {{ $labels.job }} has more the 1000 requests.'
        summary: 'Instance {{ $labels.job }} requests alert'
